feat: add specification for sign typed data message
uport-project/specs pull request #35
Opened 2018-09-27 20:50 UTC by rmw2

Add a specification for a typed data (ERC712) signature request message.  The message is a JWT much like our other messages, with the difference that the `typedData` field, (in place of `unsignedClaim`) is structured according to ERC712.  The JWT response also contains an explicit signature field, representing the signature over the `typedData` alone, while the JWT itself is signed over its entire structure, including the issuer and subject fields.

Note: The response still feels a little strange to me, I would love input from @aldigjo @simonas-notcat @pelle --  Is it fine to just wrap the concept of an ERC712 typed data and signature inside a JWT?  Specifically, do we want two signatures on a single JWT, one of them inside of the object itself? Also is there still necessarily a concept of a subject?

2018-09-27 23:25 UTC, pelle requested changes
Looks great. One small change I'd like. Can we change it to `EIP712Req`. It would allow us to do support future schemes easier,

2018-09-27 23:25 UTC, pelle commented on messages/signtypeddata.md
> +`type` | MUST have the value `signTypedDataReq` | yes
Could we maybe make this smaller. I'm even thinking `eip712Req`.

2018-09-28 20:22 UTC, pelle requested changes

2018-09-28 20:22 UTC, pelle commented on messages/signtypeddata.md
> +  "type":"verReq",
Missed this before. It should be `eip712Req` in the example as well

2018-09-28 20:23 UTC, rmw2 commented on messages/signtypeddata.md
> +  "type":"verReq",
Good catch, thanks

2018-09-28 20:38 UTC, pelle approved these changes

2018-09-28 20:38 UTC, merged