Add support for claims specs
uport-project/specs pull request #48
Opened 2019-04-13 17:04 UTC by pelle

We need a way to request various data about a claim. This allows us to specify most importantly an issuer, but also if the claim is required for signup.

A Claims Spec allows you to set specific requirements for the claims you are requesting.

Name | Description | Required
---- | ----------- | --------
type | The claims type | yes
essential | This claim is essential. A response should not be returned if user does not have this claim | no
iss | Array of DID's of allowed issuers of claims | no
url | URL for obtaining claim | no
reason | Short string explaining why you need this | no

Examples:

```js
{
  type: 'email',
  essential: true,
  iss: ['did:web:uport.claims'],
  url: 'https://uport.claims/email',
  reason: 'Whe need to be able to email you' 
}
```

2019-04-14 11:23 UTC, oed commented
Do you think something like this will be included in the DID-Auth spec? 
cc @awoie

2019-04-15 07:42 UTC, simonas-notcat requested changes
If the `iss` field is an array, I think `url` should also be an array. Or something like this:

```javascript
{
  type: 'email',
  essential: true,
  iss: [
    {
      did: 'did:web:uport.claims',
      url: 'https://uport.claims/email'
    },
    {
      did: 'did:web:sobol.io',
      url: 'https://sobol.io/verify'
    }
  ],
  reason: 'Whe need to be able to email you' 
}
```

2019-04-15 14:34 UTC, awoie commented
@oed DID Auth is about exchanging a DID, while the Claims and Credentials people are talking about how to exchange credentials. But I assume that something like this will be included in the spec, yes.

2019-04-15 14:37 UTC, awoie commented
It might be worth looking at the current claim manifest proposal and the way how they structure the request: https://hackmd.io/q-selsVyQQ-1p1LK7mHJxw

2019-04-15 14:38 UTC, simonas-notcat approved these changes

2019-04-15 15:02 UTC, merged