Removing issc field from messages
uport-project/specs pull request #49
Opened 2019-04-15 14:59 UTC by simonas-notcat

2019-04-15 15:01 UTC, pelle requested changes

2019-04-15 15:01 UTC, pelle commented on messages/claims.md
> -## Verified Claims about Issuer
Don't we still need this section?

2019-04-15 15:02 UTC, simonas-notcat commented on messages/claims.md
> -## Verified Claims about Issuer
I moved it to the top of the document

2019-04-19 23:29 UTC, pelle approved these changes

2019-04-19 23:29 UTC, merged